-- liquibase formatted sql
-- changeset unittree:update_db_unittree-3.1.3-3.1.4-mariaDB-mySQL.sql dbms:mariadb,mysql 
-- preconditions onFail:MARK_RAN onError:WARN
SET FOREIGN_KEY_CHECKS = 0;

SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO';
ALTER TABLE unittree_unit modify COLUMN id_unit int AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = 1;

-- changeset unittree:update_db_unittree-3.1.3-3.1.4-postgreSQL.sql dbms:postgresql
-- preconditions onFail:MARK_RAN onError:WARN

-- Default value on id_unit column is dropped because PostgreSQL doesn't allow to switch to an auto-increment 
-- column if a default value exists
ALTER TABLE unittree_unit alter id_unit drop default;

-- Switch to auto-increment primary key
ALTER TABLE unittree_unit alter id_unit add GENERATED by default AS IDENTITY(START WITH 1);

-- The query below is used to synchronize the sequence created previously with the content of unittree_unit table.
-- For the special case where there is only one row (ROOT entity) in the table (MAX(id_unit) = 0), the synchronization is not performed 
-- because the sequence is already synchronized. Furthermore, setval function doesn't allow 0 value.
SELECT CASE WHEN MAX(id_unit) > 0 
            THEN setval((SELECT PG_GET_SERIAL_SEQUENCE('"unittree_unit"', 'id_unit')), (SELECT MAX(id_unit) FROM unittree_unit)) END
FROM unittree_unit;