INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (1, 0, 'DEVE', 'DEVE');

--
-- DEVE_ATELIER_CIMETIERE
--

-- unittree_unit
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (2, 1, 'Atelier cimetière', 'Atelier cimetière');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (3, 2, 'Bagneux', 'Atelier d\'entretien général du cimetière de Bagneux');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (4, 2, 'Ivry', 'Atelier d\'entretien général du cimetière d\'Ivry');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (5, 2, 'Montparnasse', 'Atelier d\'entretien général du cimetière de Montparnasse');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (6, 2, 'Père Lachaise', 'Atelier d\'entretien général du cimetière de Père Lachaise');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (7, 2, 'Pantin', 'Atelier d\'entretien général du cimetière de Pantin');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (8, 2, 'Saint-Ouen', 'Atelier d\'entretien général du cimetière de Saint-Ouen');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (9, 2, 'Thiais', 'Atelier d\'entretien général du cimetière de Thiais');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (10, 2, 'Montmartre', 'Atelier d\'entretien général du cimetière de Montmartre');

-- unittree_unit_sector
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 3);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 4);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 5);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 6);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 7);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 8);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 9);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 10);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 3);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 4);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 5);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 6);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 7);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 8);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 9);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 10);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 3);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 4);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 5);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 6);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 7);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 8);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 9);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (2, 10);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (3, 3);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (4, 4);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (5, 5);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (6, 6);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (7, 7);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (8, 8);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (9, 9);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (10, 10);

--
-- DEVE_ATELIER_JARDINAGE
--

-- unittree_unit
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (11, 1, 'Atelier jardinage', 'Atelier jardinage');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (12, 11, 'Conservation de Bagneux', 'Atelier de jardinage Conservation de Bagneux');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (13, 11, 'Bagatelle', 'Atelier de jardinage Bagatelle');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (14, 11, 'Maillot', 'Atelier de jardinage Maillot');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (15, 11, 'Parc Floral', 'Atelier de jardinage de Parc Floral');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (16, 11, 'Champs de Mars (07ème arrondissement)', 'Atelier de jardinage du Champs de Mars (07ème arrondissement)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (17, 11, 'Plaine (Boulogne)', 'Atelier de jardinage de la plaine (Boulogne)'); 
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (18, 11, 'Pré catelan', 'Atelier de jardinage du Pré catelan');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (19, 11, 'Auteuil', 'Atelier de jardinage Auteuil');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (20, 11, 'Plaine (Vincennes)', 'Atelier de jardinage de la plaine (Vincennes)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (21, 11, '01ème et 02ème arrondissements', 'Atelier de jardinage du 01ème et 02ème arrondissements');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (22, 11, '04ème arrondissement', 'Atelier de jardinage du 04ème arrondissement');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (23, 11, '05ème arrondissement', 'Atelier de jardinage du 05ème arrondissement');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (24, 11, '08ème et 09ème arrondissements (hors Champs Elysées)', 'Atelier de jardinage du 08ème et 09ème arrondissements (hors Champs Elysées)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (25, 11, '10ème arrondissement', 'Atelier de jardinage du 10ème arrondissement');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (26, 11, '11ème arrondissement Est', 'Atelier de jardinage du 11ème arrondissement Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (27, 11, 'Conservation d\'Ivry', 'Atelier de jardinage Conservation d\'Ivry');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (28, 11, 'Conservation de Saint-Ouen', 'Atelier de jardinage Conservation de Saint-Ouen');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (29, 11, 'Conservation de Thiais', 'Atelier de jardinage Conservation de Thiais');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (30, 11, '07ème arrondissement (hors Champs de Mars)', 'Atelier de jardinage du 07ème arrondissement (hors Champs de Mars)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (31, 11, 'Parc de Bercy(12ème arrondissement)', 'Atelier de jardinage du parc de Bercy(12ème arrondissement)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (32, 11, 'Conservation de Pantin', 'Atelier de jardinage Conservation de Pantin');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (33, 11, 'Saint-Mandé', 'Atelier de jardinage de Saint-Mandé');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (34, 11, 'Minimes', 'Atelier de jardinage des Minimes');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (35, 11, 'Conservation Père Lachaise', 'Atelier de jardinage Conservation Père Lachaise');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (36, 11, '13ème arrondissement Nord', 'Atelier de jardinage du 13ème arrondissement Nord');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (37, 11, '16ème arrondissement Sud', 'Atelier de jardinage du 16ème arrondissement Sud');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (38, 11, '17ème arrondissement Ouest', 'Atelier de jardinage du 17ème arrondissement Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (39, 11, '20ème arrondissement Est', 'Atelier de jardinage du 20ème arrondissement Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (40, 11, 'Ecole Breuil Serres-Floriculture', 'Atelier de jardinage de l\'école Breuil Serres-Floriculture');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (41, 11, 'Parc André CitroÙn (15ème arrondissement)', 'Atelier de jardinage du parc André CitroÙn (15ème arrondissement)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (42, 11, '12ème arrondissement Est', 'Atelier de jardinage du 12ème arrondissement Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (43, 11, '18ème arrondissement Est', 'Atelier de jardinage du 18ème arrondissement Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (44, 11, '13ème arrondissement Est', 'Atelier de jardinage du 13ème arrondissement Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (45, 11, '15ème arrondissement Sud-Ouest', 'Atelier de jardinage du 15ème arrondissement Sud-Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (46, 11, '16ème arrondissement Est', 'Atelier de jardinage du 16ème arrondissement Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (47, 11, '16ème arrondissement Nord', 'Atelier de jardinage du 16ème arrondissement Nord');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (48, 11, '16ème arrondissement Ouest', 'Atelier de jardinage du 16ème arrondissement Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (49, 11, '17ème arrondissement Est', 'Atelier de jardinage du 17ème arrondissement Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (50, 11, '17ème arrondissement Nord-Ouest', 'Atelier de jardinage du 17ème arrondissement Nord-Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (51, 11, '18ème arrondissement Nord', 'Atelier de jardinage du 18ème arrondissement Nord');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (52, 11, '18ème arrondissement Sud', 'Atelier de jardinage du 18ème arrondissement Sud');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (53, 11, 'Parc des Buttes-Chaumont (19ème arrondissement)', 'Atelier de jardinage du parc des Buttes-Chaumont (19ème arrondissement)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (54, 11, '20ème arrondissement Ouest', 'Atelier de jardinage du 20ème arrondissement Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (55, 11, '13ème arrondissement Ouest', 'Atelier de jardinage du 13ème arrondissement Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (56, 11, 'Parc Montsouris (14ème arrondissement)', 'Atelier de jardinage du parc Montsouris (14ème arrondissement)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (57, 11, '03ème arrondissement', 'Atelier de jardinage du 03ème arrondissement');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (58, 11, '06ème arrondissement', 'Atelier de jardinage du 06ème arrondissement');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (59, 11, 'Champs Elysées (08ème arrondissement)', 'Atelier de jardinage Champs Elysées (08ème arrondissement)');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (60, 11, 'Conservation de Montmartre', 'Atelier de jardinage Conservation de Montmartre');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (61, 11, 'Conservation de Montparnasse', 'Atelier de jardinage Conservation de Montparnasse');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (62, 11, '19ème arrondissement Sud', 'Atelier de jardinage du 19ème arrondissement Sud');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (63, 11, '20ème arrondissement Nord', 'Atelier de jardinage du 20ème arrondissement Nord');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (64, 11, '20ème arrondissement Sud', 'Atelier de jardinage du 20ème arrondissement Sud');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (65, 11, 'Ecole Breuil Arboretum-Ornement', 'Atelier de jardinage de l\'école Breuil Arboretum-Ornement');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (66, 11, '15ème arrondissement Centre-Est', 'Atelier de jardinage du 15ème arrondissement Centre-Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (67, 11, '15ème arrondissement Nord-Ouest', 'Atelier de jardinage du 15ème arrondissement Nord-Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (68, 11, '11ème arrondissement Ouest', 'Atelier de jardinage du 11ème arrondissement Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (69, 11, '12ème arrondissement Nord', 'Atelier de jardinage du 12ème arrondissement Nord');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (70, 11, '12ème arrondissement Ouest', 'Atelier de jardinage du 12ème arrondissement Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (71, 11, '14ème arrondissement Nord', 'Atelier de jardinage du 14ème arrondissement Nord');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (72, 11, '14ème arrondissement Sud', 'Atelier de jardinage du 14ème arrondissement Sud');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (73, 11, '15ème arrondissement Nord-Est', 'Atelier de jardinage du 15ème arrondissement Nord-Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (74, 11, '15ème arrondissement Sud Est', 'Atelier de jardinage du 15ème arrondissement Sud Est');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (75, 11, '19ème arrondissement Nord', 'Atelier de jardinage du 19ème arrondissement Nord');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (76, 11, '19ème arrondissement Ouest', 'Atelier de jardinage du 19ème arrondissement Ouest');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (77, 11, 'Ecole Breuil Roseraie-Potager-Verger', 'Atelier de jardinage de l\'école Breuil Roseraie-Potager-Verger');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (78, 11, '13ème arrondissement Sud', 'Atelier de jardinage du 13ème arrondissement Sud');

-- unittree_unit_sector
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 12);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 13);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 14);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 15);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 16);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 17);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 18);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 19);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 20);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 21);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 22);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 23);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 24);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 25);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 26);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 27);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 28);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 29);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 30);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 31);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 32);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 33);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 34);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 35);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 36);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 37);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 38);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 39);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 40);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 41);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 42);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 43);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 44);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 45);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 46);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 47);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 48);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 49);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 50);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 51);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 52);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 53);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 54);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 55);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 56);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 57);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 58);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 59);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 60);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 61);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 62);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 63);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 64);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 65);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 66);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 67);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 68);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 69);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 70);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 71);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 72);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 73);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 74);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 75);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 76);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 77);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 78);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 12);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 13);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 14);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 15);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 16);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 17);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 18);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 19);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 20);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 21);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 22);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 23);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 24);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 25);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 26);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 27);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 28);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 29);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 30);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 31);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 32);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 33);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 34);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 35);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 36);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 37);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 38);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 39);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 40);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 41);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 42);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 43);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 44);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 45);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 46);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 47);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 48);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 49);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 50);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 51);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 52);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 53);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 54);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 55);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 56);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 57);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 58);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 59);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 60);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 61);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 62);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 63);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 64);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 65);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 66);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 67);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 68);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 69);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 70);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 71);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 72);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 73);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 74);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 75);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 76);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 77);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 78);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 12);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 13);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 14);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 15);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 16);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 17);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 18);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 19);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 20);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 21);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 22);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 23);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 24);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 25);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 26);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 27);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 28);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 29);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 30);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 31);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 32);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 33);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 34);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 35);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 36);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 37);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 38);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 39);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 40);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 41);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 42);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 43);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 44);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 45);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 46);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 47);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 48);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 49);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 50);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 51);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 52);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 53);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 54);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 55);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 56);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 57);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 58);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 59);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 60);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 61);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 62);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 63);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 64);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 65);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 66);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 67);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 68);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 69);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 70);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 71);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 72);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 73);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 74);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 75);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 76);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 77);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (11, 78);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (12, 12);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (13, 13);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (14, 14);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (15, 15);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (16, 16);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (17, 17);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (18, 18);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (19, 19);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (20, 20);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (21, 21);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (22, 22);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (23, 23);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (24, 24);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (25, 25);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (26, 26);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (27, 27);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (28, 28);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (29, 29);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (30, 30);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (31, 31);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (32, 32);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (33, 33);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (34, 34);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (35, 35);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (36, 36);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (37, 37);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (38, 38);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (39, 39);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (40, 40);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (41, 41);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (42, 42);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (43, 43);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (44, 44);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (45, 45);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (46, 46);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (47, 47);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (48, 48);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (49, 49);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (50, 50);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (51, 51);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (52, 52);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (53, 53);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (54, 54);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (55, 55);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (56, 56);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (57, 57);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (58, 58);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (59, 59);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (60, 60);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (61, 61);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (62, 62);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (63, 63);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (64, 64);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (65, 65);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (66, 66);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (67, 67);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (68, 68);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (69, 69);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (70, 70);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (71, 71);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (72, 72);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (73, 73);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (74, 74);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (75, 75);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (76, 76);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (77, 77);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (78, 78);

--
-- DEVE_SA
--

-- unittree_unit
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (79, 1, 'SA', 'SA');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (80, 79, 'Division des plantations EST', 'SA - Division des plantations EST');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (81, 79, 'Division des plantations NORD', 'SA - Division des plantations NORD');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (82, 79, 'Division des plantations SUD', 'SA - Division des plantations SUD');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (83, 79, 'Division du Bois de Boulogne', 'SA - Division du Bois de Boulogne');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (84, 79, 'Division du Bois de Vincennes', 'SA - Division du Bois de Vincennes');

-- unittree_unit_sector
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 80);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 81);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 82);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 83);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 84);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 80);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 81);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 82);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 83);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 84);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (79, 80);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (79, 81);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (79, 82);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (79, 83);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (79, 84);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (80, 80);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (81, 81);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (82, 82);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (83, 83);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (84, 84);

--
-- DEVE_SC
--

-- unittree_unit
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (85, 1, 'SC', 'SC');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (86, 85, 'Conservation de Bagneux', 'SC - Conservation de Bagneux');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (87, 85, 'Conservation de Ivry', 'SC - Conservation de Ivry');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (88, 85, 'Conservation de Thiais', 'SC - Conservation de Thiais');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (89, 85, 'Conservation de Pantin', 'SC - Conservation de Pantin');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (90, 85, 'Conservation de Saint-Ouen', 'SC - Conservation de Saint-Ouen');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (91, 85, 'Conservation de Montmartre', 'SC - Conservation de Montmartre');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (92, 85, 'Conservation de Père-Lachaise', 'SC - Conservation de Père-Lachaise');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (93, 85, 'Conservation de Montparnasse', 'SC - Conservation de Montparnasse');

-- unittree_unit_sector
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 86);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 87);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 88);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 89);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 90);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 91);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 92);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 93);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 86);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 87);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 88);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 89);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 90);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 91);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 92);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 93);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 86);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 87);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 88);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 89);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 90);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 91);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 92);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (85, 93);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (86, 86);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (87, 87);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (88, 88);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (89, 89);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (90, 90);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (91, 91);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (92, 92);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (93, 93);

--
-- DEVE_SEJ
--

-- unittree_unit
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (94, 1, 'SEJ', 'SEJ');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (95, 94, 'Division 11e', 'SEJ - Division 11e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (96, 94, 'Division 12e', 'SEJ - Division 12e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (97, 94, 'Division 13e', 'SEJ - Division 13e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (98, 94, 'Division 14e', 'SEJ - Division 14e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (99, 94, 'Division 15e', 'SEJ - Division 15e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (100, 94, 'Division 16e', 'SEJ - Division 16e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (101, 94, 'Division 17e', 'SEJ - Division 17e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (102, 94, 'Division 18e', 'SEJ - Division 18e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (103, 94, 'Division 19e', 'SEJ - Division 19e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (104, 94, 'Division 1e 2e 3e 4e', 'SEJ - Division 1e 2e 3e 4e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (105, 94, 'Division 20e', 'SEJ - Division 20e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (106, 94, 'Division 5e 6e 7e', 'SEJ - Division 5e 6e 7e');
INSERT INTO unittree_unit (id_unit,	id_parent, label, description) VALUES (107, 94, 'Division 8e 9e 10e', 'SEJ - Division 8e 9e 10e');

-- unittree_unit_sector
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 95);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 96);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 97);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 98);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 99);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 100);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 101);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 102);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 103);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 104);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 105);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 106);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (0, 107);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 95);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 96);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 97);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 98);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 99);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 100);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 101);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 102);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 103);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 104);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 105);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 106);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (1, 107);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 95);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 96);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 97);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 98);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 99);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 100);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 101);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 102);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 103);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 104);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 105);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 106);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (94, 107);

INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (95, 95);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (96, 96);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (97, 97);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (98, 98);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (99, 99);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (100, 100);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (101, 101);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (102, 102);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (103, 103);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (104, 104);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (105, 105);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (106, 106);
INSERT INTO unittree_unit_sector (id_unit, id_sector) VALUES (107, 107);
